export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  country: string;
  amount: string;
  levels: ('bachelor' | 'master' | 'phd')[];
  deadline: string;
  minCGPA: number; // on 4.0 scale
  minIELTS: number;
  tags: string[];
  description: string;
  fields: string[]; // eligible fields
}

export const SCHOLARSHIPS: Scholarship[] = [
  // ── UNITED KINGDOM ──────────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    country: 'United Kingdom',
    amount: 'Full funding + stipend',
    levels: ['master'],
    deadline: 'Nov 5',
    minCGPA: 2.75,
    minIELTS: 6.5,
    tags: ['Leadership', 'Government', 'Full Funding'],
    description: 'The UK government\'s flagship scholarship for future global leaders.',
    fields: ['All fields'],
  },
  {
    id: '2',
    name: 'Gates Cambridge Scholarship',
    provider: 'Gates Foundation & University of Cambridge',
    country: 'United Kingdom',
    amount: 'Full funding + allowances',
    levels: ['master', 'phd'],
    deadline: 'Oct 12',
    minCGPA: 3.7,
    minIELTS: 7.5,
    tags: ['Elite', 'Research', 'Leadership'],
    description: 'One of the world\'s most prestigious international scholarships at Cambridge.',
    fields: ['All fields'],
  },
  {
    id: '3',
    name: 'Rhodes Scholarship',
    provider: 'Rhodes Trust',
    country: 'United Kingdom',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Aug 1',
    minCGPA: 3.7,
    minIELTS: 7.0,
    tags: ['Elite', 'Oxford', 'Leadership'],
    description: 'The oldest and most celebrated international fellowship at Oxford University.',
    fields: ['All fields'],
  },
  {
    id: '4',
    name: 'Commonwealth Scholarship',
    provider: 'Commonwealth Secretariat',
    country: 'United Kingdom',
    amount: 'Full funding + flights',
    levels: ['master', 'phd'],
    deadline: 'Dec 12',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Commonwealth', 'Development', 'Full Funding'],
    description: 'For students from Commonwealth countries to study in the UK.',
    fields: ['Development', 'Science', 'Technology', 'All fields'],
  },
  {
    id: '5',
    name: 'Marshall Scholarship',
    provider: 'Marshall Aid Commemoration Commission',
    country: 'United Kingdom',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Sep 25',
    minCGPA: 3.7,
    minIELTS: 7.0,
    tags: ['USA Citizens', 'Elite', 'Research'],
    description: 'Funds American scholars to study at any UK university.',
    fields: ['All fields'],
  },
  {
    id: '6',
    name: 'Clarendon Fund Scholarship',
    provider: 'University of Oxford',
    country: 'United Kingdom',
    amount: 'Full fees + £17,000/year',
    levels: ['master', 'phd'],
    deadline: 'Jan 20',
    minCGPA: 3.7,
    minIELTS: 7.5,
    tags: ['Oxford', 'Elite', 'Research'],
    description: 'Oxford University\'s flagship scholarship for graduate students worldwide.',
    fields: ['All fields'],
  },
  {
    id: '7',
    name: 'Nottingham Developing Solutions',
    provider: 'University of Nottingham',
    country: 'United Kingdom',
    amount: '50% or full tuition',
    levels: ['master'],
    deadline: 'Mar 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Development', 'Africa', 'Asia'],
    description: 'For students from developing countries to study at Nottingham.',
    fields: ['All fields'],
  },
  {
    id: '8',
    name: 'Edinburgh Global Research Scholarship',
    provider: 'University of Edinburgh',
    country: 'United Kingdom',
    amount: 'Full tuition waiver',
    levels: ['phd'],
    deadline: 'Jan 31',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Research', 'PhD', 'Competitive'],
    description: 'Competitive scholarship for outstanding PhD students at Edinburgh.',
    fields: ['All fields'],
  },
  {
    id: '9',
    name: 'Warwick Chancellor\'s International Scholarship',
    provider: 'University of Warwick',
    country: 'United Kingdom',
    amount: 'Full fees + £7,000/year',
    levels: ['phd'],
    deadline: 'Jan 20',
    minCGPA: 3.5,
    minIELTS: 6.5,
    tags: ['PhD', 'Research', 'Warwick'],
    description: 'Supports outstanding international doctoral researchers at Warwick.',
    fields: ['All fields'],
  },
  {
    id: '10',
    name: 'Manchester Masters Scholarship',
    provider: 'University of Manchester',
    country: 'United Kingdom',
    amount: '£5,000–£10,000',
    levels: ['master'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Masters', 'Merit-Based'],
    description: 'Merit-based scholarships for international master\'s students at Manchester.',
    fields: ['All fields'],
  },

  // ── EUROPE ──────────────────────────────────────────────────────────────────
  {
    id: '11',
    name: 'Erasmus Mundus',
    provider: 'European Commission',
    country: 'Europe',
    amount: '€1,400/month + travel',
    levels: ['master', 'phd'],
    deadline: 'Jan 10',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['European Union', 'Research', 'Multi-Country'],
    description: 'Joint master and doctoral programmes offered by top European universities.',
    fields: ['All fields'],
  },
  {
    id: '12',
    name: 'DAAD Scholarship',
    provider: 'German Academic Exchange Service',
    country: 'Germany',
    amount: '€934/month',
    levels: ['master', 'phd'],
    deadline: 'Oct 15',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['STEM', 'Germany', 'Research'],
    description: 'Germany\'s premier scholarship for international graduate students.',
    fields: ['Engineering', 'Sciences', 'Social Sciences', 'All fields'],
  },
  {
    id: '13',
    name: 'Swiss Government Excellence Scholarship',
    provider: 'Swiss Confederation',
    country: 'Switzerland',
    amount: 'CHF 1,920/month',
    levels: ['master', 'phd'],
    deadline: 'Nov 15',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Europe', 'Research', 'Innovation'],
    description: 'For researchers and artists to pursue studies at Swiss institutions.',
    fields: ['Science', 'Technology', 'Arts', 'All fields'],
  },
  {
    id: '14',
    name: 'Swedish Institute Scholarship',
    provider: 'Swedish Institute',
    country: 'Sweden',
    amount: 'SEK 11,000/month',
    levels: ['master'],
    deadline: 'Feb 10',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Scandinavia', 'Leadership', 'Sustainability'],
    description: 'For professionals from select countries to study master\'s programmes in Sweden.',
    fields: ['Sustainability', 'Healthcare', 'Social Sciences', 'All fields'],
  },
  {
    id: '15',
    name: 'Orange Tulip Scholarship',
    provider: 'Nuffic Neso Netherlands',
    country: 'Netherlands',
    amount: 'Partial to full tuition',
    levels: ['bachelor', 'master'],
    deadline: 'Mar 1',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Netherlands', 'Partial Funding'],
    description: 'For talented students from select countries to study in the Netherlands.',
    fields: ['All fields'],
  },
  {
    id: '16',
    name: 'Eiffel Excellence Scholarship',
    provider: 'French Ministry of Europe & Foreign Affairs',
    country: 'France',
    amount: '€1,181/month',
    levels: ['master', 'phd'],
    deadline: 'Jan 13',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['France', 'Excellence', 'Research'],
    description: 'Attracts top foreign students to French higher education in science and business.',
    fields: ['Engineering', 'Sciences', 'Business', 'Law', 'Political Sciences'],
  },
  {
    id: '17',
    name: 'VLIR-UOS Scholarship',
    provider: 'Flemish Interuniversity Council',
    country: 'Belgium',
    amount: 'Full funding + living costs',
    levels: ['master', 'phd'],
    deadline: 'Feb 1',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Belgium', 'Development', 'Full Funding'],
    description: 'For students from developing countries to study at Flemish universities.',
    fields: ['Development', 'Sciences', 'Agriculture', 'All fields'],
  },
  {
    id: '18',
    name: 'Austrian Government Scholarship',
    provider: 'Austrian Exchange Service (OeAD)',
    country: 'Austria',
    amount: '€1,150/month',
    levels: ['master', 'phd'],
    deadline: 'Mar 1',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Austria', 'Research', 'Exchange'],
    description: 'Supports international graduate students and researchers at Austrian universities.',
    fields: ['All fields'],
  },
  {
    id: '19',
    name: 'Denmark Government Scholarship',
    provider: 'Ministry of Higher Education and Science, Denmark',
    country: 'Denmark',
    amount: 'DKK 6,000/month',
    levels: ['master', 'phd'],
    deadline: 'Apr 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Denmark', 'Innovation', 'Research'],
    description: 'Scholarships for talented non-EU students to study at Danish universities.',
    fields: ['STEM', 'Business', 'Design', 'All fields'],
  },
  {
    id: '20',
    name: 'Finnish Government Scholarship',
    provider: 'CIMO Finland',
    country: 'Finland',
    amount: '€1,500/month',
    levels: ['phd'],
    deadline: 'Jan 31',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Finland', 'Research', 'PhD'],
    description: 'For doctoral and postdoctoral researchers at Finnish universities.',
    fields: ['All fields'],
  },
  {
    id: '21',
    name: 'Italian Government Scholarship',
    provider: 'Italian Ministry of Foreign Affairs',
    country: 'Italy',
    amount: '€900/month',
    levels: ['master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Italy', 'Culture', 'Arts'],
    description: 'Italian government scholarships for foreign students in Italy.',
    fields: ['Arts', 'Architecture', 'Humanities', 'Sciences', 'All fields'],
  },
  {
    id: '22',
    name: 'Hungarian Government Scholarship (Stipendium Hungaricum)',
    provider: 'Tempus Public Foundation',
    country: 'Hungary',
    amount: 'Full funding + HUF 40,000/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Jan 15',
    minCGPA: 2.5,
    minIELTS: 5.5,
    tags: ['Hungary', 'Full Funding', 'Government'],
    description: 'Hungary\'s flagship scholarship programme for international students.',
    fields: ['All fields'],
  },
  {
    id: '23',
    name: 'Polish Government Scholarship',
    provider: 'NAWA – Polish National Agency',
    country: 'Poland',
    amount: 'PLN 1,650/month',
    levels: ['master', 'phd'],
    deadline: 'Apr 5',
    minCGPA: 3.0,
    minIELTS: 5.5,
    tags: ['Poland', 'Eastern Europe', 'Research'],
    description: 'For students from developing countries to study in Poland.',
    fields: ['All fields'],
  },
  {
    id: '24',
    name: 'Czech Government Scholarship',
    provider: 'Czech Ministry of Education',
    country: 'Czech Republic',
    amount: 'CZK 14,000/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Dec 30',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Czech Republic', 'Eastern Europe'],
    description: 'Full scholarships for students from developing countries in Czech Republic.',
    fields: ['All fields'],
  },
  {
    id: '25',
    name: 'ETH Zurich Excellence Scholarship',
    provider: 'ETH Zurich',
    country: 'Switzerland',
    amount: 'CHF 11,000/semester',
    levels: ['master'],
    deadline: 'Dec 15',
    minCGPA: 3.7,
    minIELTS: 7.0,
    tags: ['Engineering', 'Science', 'Elite'],
    description: 'For exceptional students admitted to master\'s programmes at ETH Zurich.',
    fields: ['Engineering', 'Science', 'Technology', 'Mathematics'],
  },
  {
    id: '26',
    name: 'KU Leuven Scholarship',
    provider: 'KU Leuven',
    country: 'Belgium',
    amount: '€8,000–€15,000',
    levels: ['master', 'phd'],
    deadline: 'Feb 1',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Belgium', 'Research', 'Merit'],
    description: 'Merit-based scholarships for international students at KU Leuven.',
    fields: ['All fields'],
  },

  // ── UNITED STATES & CANADA ──────────────────────────────────────────────────
  {
    id: '27',
    name: 'Fulbright Program',
    provider: 'U.S. Department of State',
    country: 'United States',
    amount: 'Full funding + travel',
    levels: ['master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 3.2,
    minIELTS: 7.0,
    tags: ['Cultural Exchange', 'USA', 'Prestigious'],
    description: 'America\'s flagship international educational exchange scholarship.',
    fields: ['All fields'],
  },
  {
    id: '28',
    name: 'Knight-Hennessy Scholars',
    provider: 'Stanford University',
    country: 'United States',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Oct 11',
    minCGPA: 3.8,
    minIELTS: 7.5,
    tags: ['Stanford', 'Elite', 'Leadership'],
    description: 'Stanford\'s prestigious multi-year fellowship for global community leaders.',
    fields: ['All fields'],
  },
  {
    id: '29',
    name: 'Schwarzman Scholars',
    provider: 'Schwarzman Foundation',
    country: 'United States',
    amount: 'Full funding + living allowance',
    levels: ['master'],
    deadline: 'Sep 28',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Leadership', 'China Focus', 'Elite'],
    description: 'One-year master\'s programme at Tsinghua University for future global leaders.',
    fields: ['All fields'],
  },
  {
    id: '30',
    name: 'Hubert Humphrey Fellowship',
    provider: 'U.S. Department of State',
    country: 'United States',
    amount: 'Full funding',
    levels: ['master'],
    deadline: 'Jul 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['USA', 'Professional', 'Leadership'],
    description: 'For mid-career professionals from developing countries to study in the USA.',
    fields: ['Public Policy', 'Education', 'Agriculture', 'Communications'],
  },
  {
    id: '31',
    name: 'Harvard University Fellowship',
    provider: 'Harvard University',
    country: 'United States',
    amount: 'Up to $50,000/year',
    levels: ['master', 'phd'],
    deadline: 'Jan 2',
    minCGPA: 3.7,
    minIELTS: 7.5,
    tags: ['Harvard', 'Elite', 'Research'],
    description: 'Need and merit-based fellowships for graduate students at Harvard.',
    fields: ['All fields'],
  },
  {
    id: '32',
    name: 'Yale World Fellows Program',
    provider: 'Yale University',
    country: 'United States',
    amount: 'Full fellowship + stipend',
    levels: ['master'],
    deadline: 'Feb 5',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Yale', 'Leadership', 'Global'],
    description: 'For accomplished mid-career global leaders in New Haven.',
    fields: ['All fields'],
  },
  {
    id: '33',
    name: 'Princeton University Fellowship',
    provider: 'Princeton University',
    country: 'United States',
    amount: 'Full tuition + $36,000/year',
    levels: ['phd'],
    deadline: 'Dec 15',
    minCGPA: 3.7,
    minIELTS: 7.5,
    tags: ['Princeton', 'PhD', 'Elite'],
    description: 'Comprehensive doctoral fellowships for exceptional PhD students at Princeton.',
    fields: ['All fields'],
  },
  {
    id: '34',
    name: 'Vanier Canada Graduate Scholarship',
    provider: 'Government of Canada',
    country: 'Canada',
    amount: 'CAD $50,000/year',
    levels: ['phd'],
    deadline: 'Nov 1',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Research', 'PhD', 'Prestigious'],
    description: 'Canada\'s top doctoral scholarship for world-class researchers.',
    fields: ['Health Sciences', 'Natural Sciences', 'Engineering', 'Social Sciences'],
  },
  {
    id: '35',
    name: 'Trudeau Foundation Scholarship',
    provider: 'Pierre Elliott Trudeau Foundation',
    country: 'Canada',
    amount: 'CAD $60,000/year',
    levels: ['phd'],
    deadline: 'Dec 1',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Canada', 'Social Sciences', 'Leadership'],
    description: 'For outstanding doctoral students in humanities and social sciences in Canada.',
    fields: ['Humanities', 'Social Sciences', 'Law', 'Public Policy'],
  },
  {
    id: '36',
    name: 'McCall MacBain Scholarships',
    provider: 'McCall MacBain Foundation',
    country: 'Canada',
    amount: 'Full funding + CAD $15,000',
    levels: ['master'],
    deadline: 'Oct 1',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Canada', 'McGill', 'Leadership'],
    description: 'Canada\'s largest entrance scholarship at McGill University.',
    fields: ['All fields'],
  },

  // ── ASIA ────────────────────────────────────────────────────────────────────
  {
    id: '37',
    name: 'Japanese Government (MEXT)',
    provider: 'Japanese Ministry of Education',
    country: 'Japan',
    amount: '¥143,000/month + tuition',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'May 15',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Government', 'Asia', 'Research'],
    description: 'Japan\'s government scholarship for international students at all levels.',
    fields: ['STEM', 'All fields'],
  },
  {
    id: '38',
    name: 'Korean Government Scholarship (KGSP)',
    provider: 'National Institute for International Education (NIIED)',
    country: 'South Korea',
    amount: 'Full funding + KRW 900k/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Mar 5',
    minCGPA: 2.64,
    minIELTS: 5.5,
    tags: ['Government', 'Asia', 'Language'],
    description: 'South Korea\'s full scholarship for undergraduate and graduate students.',
    fields: ['All fields'],
  },
  {
    id: '39',
    name: 'Chinese Government Scholarship (CSC)',
    provider: 'China Scholarship Council',
    country: 'China',
    amount: 'Full tuition + CNY 3,000/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['China', 'Government', 'Full Funding'],
    description: 'Chinese government fully-funded scholarships for international students.',
    fields: ['All fields'],
  },
  {
    id: '40',
    name: 'Singapore Government Scholarship',
    provider: 'Singapore Government',
    country: 'Singapore',
    amount: 'Full tuition + SGD 1,500/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Mar 31',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Singapore', 'Government', 'ASEAN'],
    description: 'Prestigious scholarships for top international students to study in Singapore.',
    fields: ['STEM', 'Business', 'Social Sciences', 'All fields'],
  },
  {
    id: '41',
    name: 'NUS Research Scholarship',
    provider: 'National University of Singapore',
    country: 'Singapore',
    amount: 'Full tuition + SGD 2,200/month',
    levels: ['phd'],
    deadline: 'Dec 31',
    minCGPA: 3.5,
    minIELTS: 6.5,
    tags: ['Singapore', 'Research', 'PhD'],
    description: 'Research scholarships for doctoral students at NUS.',
    fields: ['Science', 'Engineering', 'Computing', 'Medicine', 'All fields'],
  },
  {
    id: '42',
    name: 'ADB-JSP Scholarship',
    provider: 'Asian Development Bank & Japan',
    country: 'Multiple Countries',
    amount: 'Full tuition + $1,000/month',
    levels: ['master'],
    deadline: 'Jan 15',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Development', 'Asia', 'Japan'],
    description: 'For development professionals from ADB member countries for graduate study.',
    fields: ['Development', 'Business', 'Economics', 'Engineering'],
  },
  {
    id: '43',
    name: 'Taiwan ICDF Scholarship',
    provider: 'International Cooperation and Development Fund',
    country: 'Taiwan',
    amount: 'Full funding + TWD 15,000/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Taiwan', 'Development', 'Government'],
    description: 'Taiwan\'s international scholarship for students from allied countries.',
    fields: ['Agriculture', 'Public Health', 'Environmental Studies', 'All fields'],
  },
  {
    id: '44',
    name: 'Thailand Government Scholarship',
    provider: 'Royal Thai Government',
    country: 'Thailand',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Thailand', 'ASEAN', 'Government'],
    description: 'Thai government scholarships for ASEAN and developing country students.',
    fields: ['STEM', 'Agriculture', 'Public Health', 'All fields'],
  },
  {
    id: '45',
    name: 'Malaysia International Scholarship (MIS)',
    provider: 'Malaysian Ministry of Higher Education',
    country: 'Malaysia',
    amount: 'Full tuition + MYR 1,500/month',
    levels: ['master', 'phd'],
    deadline: 'Jun 30',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Malaysia', 'Government', 'ASEAN'],
    description: 'Malaysia\'s fully-funded scholarship for international postgraduate students.',
    fields: ['STEM', 'Business', 'Agriculture', 'Islamic Studies'],
  },
  {
    id: '46',
    name: 'Türkiye Bursları Scholarship',
    provider: 'Turkish Government',
    country: 'Turkey',
    amount: 'Full funding + TRY 1,200/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Feb 20',
    minCGPA: 2.5,
    minIELTS: 5.0,
    tags: ['Turkey', 'Government', 'Full Funding'],
    description: 'Turkey\'s government scholarship for international students at all levels.',
    fields: ['All fields'],
  },
  {
    id: '47',
    name: 'India ICCR Scholarship',
    provider: 'Indian Council for Cultural Relations',
    country: 'India',
    amount: 'Full tuition + INR 8,000/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Feb 15',
    minCGPA: 2.5,
    minIELTS: 5.5,
    tags: ['India', 'Culture', 'Government'],
    description: 'India\'s cultural scholarship for international students at Indian universities.',
    fields: ['All fields'],
  },

  // ── AUSTRALIA / NEW ZEALAND ─────────────────────────────────────────────────
  {
    id: '48',
    name: 'Australia Awards',
    provider: 'Australian Government',
    country: 'Australia',
    amount: 'Full funding + living allowance',
    levels: ['master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 2.75,
    minIELTS: 6.5,
    tags: ['Government', 'Pacific', 'Full Funding'],
    description: 'Supporting development through education in Australia.',
    fields: ['Development', 'Agriculture', 'Health', 'Engineering'],
  },
  {
    id: '49',
    name: 'Endeavour Leadership Program',
    provider: 'Australian Government',
    country: 'Australia',
    amount: 'AUD $24,500 – $272,500',
    levels: ['master', 'phd'],
    deadline: 'Jun 30',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Australia', 'Leadership', 'Research'],
    description: 'Fully-funded postgraduate scholarships and fellowships in Australia.',
    fields: ['All fields'],
  },
  {
    id: '50',
    name: 'New Zealand Excellence Awards',
    provider: 'New Zealand Government',
    country: 'New Zealand',
    amount: 'NZD $10,000 – $20,000',
    levels: ['master', 'phd'],
    deadline: 'Mar 1',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['New Zealand', 'Merit', 'Government'],
    description: 'Recognising excellence in students choosing to study in New Zealand.',
    fields: ['All fields'],
  },
  {
    id: '51',
    name: 'Monash International Merit Scholarship',
    provider: 'Monash University',
    country: 'Australia',
    amount: 'AUD $10,000/year',
    levels: ['bachelor', 'master'],
    deadline: 'May 31',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Australia', 'Merit', 'University'],
    description: 'Merit-based scholarships for exceptional international students at Monash.',
    fields: ['All fields'],
  },
  {
    id: '52',
    name: 'Melbourne Research Scholarship',
    provider: 'University of Melbourne',
    country: 'Australia',
    amount: 'Full tuition + AUD $32,500/year',
    levels: ['phd'],
    deadline: 'Oct 31',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Research', 'PhD', 'Australia'],
    description: 'Top research scholarships for doctoral students at the University of Melbourne.',
    fields: ['All fields'],
  },

  // ── AFRICA & MIDDLE EAST ────────────────────────────────────────────────────
  {
    id: '53',
    name: 'Mastercard Foundation Scholarship',
    provider: 'Mastercard Foundation',
    country: 'Multiple Countries',
    amount: 'Full funding + living costs',
    levels: ['bachelor', 'master'],
    deadline: 'Nov 30',
    minCGPA: 2.5,
    minIELTS: 6.0,
    tags: ['Africa', 'Social Impact', 'Full Funding'],
    description: 'Enables talented young Africans to access world-class higher education.',
    fields: ['All fields'],
  },
  {
    id: '54',
    name: 'African Development Bank Scholarship',
    provider: 'African Development Bank',
    country: 'Multiple Countries',
    amount: 'Full funding + $1,500/month',
    levels: ['master'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Africa', 'Development', 'Economics'],
    description: 'For African professionals to study development-related masters programmes.',
    fields: ['Economics', 'Finance', 'Development', 'Public Policy'],
  },
  {
    id: '55',
    name: 'King Abdullah Scholarship (KSA)',
    provider: 'Saudi Arabian Government',
    country: 'Saudi Arabia',
    amount: 'Full funding + stipend',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'May 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Saudi Arabia', 'Government', 'Middle East'],
    description: 'Saudi Arabia\'s international scholarship for talented students worldwide.',
    fields: ['STEM', 'Medicine', 'Business', 'All fields'],
  },
  {
    id: '56',
    name: 'UAE Government Scholarship',
    provider: 'UAE Ministry of Higher Education',
    country: 'United Arab Emirates',
    amount: 'Full funding + AED 2,000/month',
    levels: ['bachelor', 'master'],
    deadline: 'Jun 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['UAE', 'Middle East', 'Government'],
    description: 'UAE government scholarship for outstanding international students.',
    fields: ['Engineering', 'Technology', 'Business', 'All fields'],
  },
  {
    id: '57',
    name: 'Qatar Foundation Scholarship',
    provider: 'Qatar Foundation',
    country: 'Qatar',
    amount: 'Full funding + stipend',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Feb 1',
    minCGPA: 3.3,
    minIELTS: 7.0,
    tags: ['Qatar', 'Middle East', 'Research'],
    description: 'Supporting academic excellence and research at Education City, Qatar.',
    fields: ['STEM', 'Business', 'Education', 'All fields'],
  },
  {
    id: '58',
    name: 'Egyptian Government Scholarship',
    provider: 'Egyptian Ministry of Higher Education',
    country: 'Egypt',
    amount: 'Full tuition + housing',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Egypt', 'Government', 'Arabic'],
    description: 'Egyptian government scholarships for international students at Egyptian universities.',
    fields: ['Arabic Studies', 'Islamic Studies', 'Medicine', 'Engineering', 'All fields'],
  },
  {
    id: '59',
    name: 'Moroccan Excellence Scholarship',
    provider: 'Moroccan Government',
    country: 'Morocco',
    amount: 'Full tuition + MAD 2,500/month',
    levels: ['master', 'phd'],
    deadline: 'Jul 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Morocco', 'Africa', 'Government'],
    description: 'Morocco\'s scholarship for African and developing country students.',
    fields: ['All fields'],
  },
  {
    id: '60',
    name: 'OFID Scholarship Award',
    provider: 'OPEC Fund for International Development',
    country: 'Multiple Countries',
    amount: '$5,000/year',
    levels: ['master'],
    deadline: 'Jun 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Development', 'Energy', 'Need-Based'],
    description: 'For developing country students in any field related to development.',
    fields: ['Economics', 'Development', 'Energy', 'Health', 'All fields'],
  },

  // ── GLOBAL / MULTI-COUNTRY ──────────────────────────────────────────────────
  {
    id: '61',
    name: 'Aga Khan Foundation Scholarship',
    provider: 'Aga Khan Foundation',
    country: 'Multiple Countries',
    amount: 'Full or partial funding',
    levels: ['master'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Development', 'Competitive', 'Need-Based'],
    description: 'For outstanding graduates committed to development of their communities.',
    fields: ['Development', 'Architecture', 'Education', 'Media'],
  },
  {
    id: '62',
    name: 'World Bank Scholarship Program',
    provider: 'World Bank',
    country: 'Multiple Countries',
    amount: 'Full funding + $1,600/month',
    levels: ['master'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Development', 'Economics', 'Global'],
    description: 'For development professionals from developing member countries.',
    fields: ['Economics', 'Finance', 'Development', 'Public Policy', 'Environmental Studies'],
  },
  {
    id: '63',
    name: 'Ford Foundation Fellowship',
    provider: 'Ford Foundation',
    country: 'United States',
    amount: '$27,000/year',
    levels: ['phd'],
    deadline: 'Dec 12',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['USA', 'Diversity', 'Research'],
    description: 'For scholars committed to diversity and inclusion pursuing doctoral studies.',
    fields: ['Social Sciences', 'Humanities', 'STEM', 'All fields'],
  },
  {
    id: '64',
    name: 'Open Society Foundations Scholarship',
    provider: 'Open Society Foundations',
    country: 'Multiple Countries',
    amount: 'Full funding',
    levels: ['master', 'phd'],
    deadline: 'Dec 15',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Open Society', 'Democracy', 'Human Rights'],
    description: 'For students from developing countries committed to open society values.',
    fields: ['Law', 'Social Sciences', 'Public Policy', 'Human Rights'],
  },
  {
    id: '65',
    name: 'CERN Doctoral Student Program',
    provider: 'CERN',
    country: 'Switzerland',
    amount: 'CHF 3,200/month',
    levels: ['phd'],
    deadline: 'Mar 15',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Physics', 'CERN', 'Research'],
    description: 'Conduct your PhD research at CERN, the world\'s leading particle physics laboratory.',
    fields: ['Physics', 'Engineering', 'Computing', 'Mathematics'],
  },
  {
    id: '66',
    name: 'UNESCO-ISEDC Fellowship',
    provider: 'UNESCO & Russia',
    country: 'Multiple Countries',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Oct 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['UNESCO', 'Science', 'Culture'],
    description: 'UNESCO Co-sponsored fellowships for education, science and culture students.',
    fields: ['Natural Sciences', 'Education', 'Cultural Studies', 'Communication'],
  },
  {
    id: '67',
    name: 'WMO Scholarship Programme',
    provider: 'World Meteorological Organization',
    country: 'Multiple Countries',
    amount: 'Full funding',
    levels: ['master'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Climate', 'Meteorology', 'UN'],
    description: 'For students from developing countries to study meteorology and hydrology.',
    fields: ['Meteorology', 'Climate Science', 'Hydrology', 'Environmental Science'],
  },
  {
    id: '68',
    name: 'WHO Internship Programme',
    provider: 'World Health Organization',
    country: 'Multiple Countries',
    amount: 'Stipend provided',
    levels: ['master', 'phd'],
    deadline: 'Ongoing',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Health', 'UN', 'Global'],
    description: 'Structured learning opportunity at WHO headquarters or regional offices.',
    fields: ['Public Health', 'Medicine', 'Epidemiology', 'Health Policy'],
  },
  {
    id: '69',
    name: 'Rotary Peace Fellowship',
    provider: 'Rotary Foundation',
    country: 'Multiple Countries',
    amount: 'Full funding + living allowance',
    levels: ['master'],
    deadline: 'May 31',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Peace', 'Conflict Resolution', 'Leadership'],
    description: 'For peace and development professionals to study at partner Rotary Peace Centres.',
    fields: ['International Relations', 'Peace Studies', 'Development', 'Social Sciences'],
  },
  {
    id: '70',
    name: 'LPDP Scholarship (Indonesia)',
    provider: 'Indonesian Ministry of Finance',
    country: 'Indonesia',
    amount: 'Full funding + IDR 2.5M/month',
    levels: ['master', 'phd'],
    deadline: 'May 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Indonesia', 'Government', 'ASEAN'],
    description: 'Indonesia\'s fully-funded scholarship for Indonesians and international students.',
    fields: ['All fields'],
  },

  // ── MORE UK UNIVERSITIES ─────────────────────────────────────────────────────
  {
    id: '71',
    name: 'LSE Scholarships',
    provider: 'London School of Economics',
    country: 'United Kingdom',
    amount: '£8,000–full tuition',
    levels: ['master'],
    deadline: 'Apr 30',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['LSE', 'Economics', 'Social Sciences'],
    description: 'Multiple competitive scholarships for international students at LSE.',
    fields: ['Economics', 'Social Sciences', 'Law', 'Business'],
  },
  {
    id: '72',
    name: 'Imperial College London PhD Scholarship',
    provider: 'Imperial College London',
    country: 'United Kingdom',
    amount: 'Full fees + £18,000/year',
    levels: ['phd'],
    deadline: 'Jan 15',
    minCGPA: 3.7,
    minIELTS: 7.0,
    tags: ['STEM', 'PhD', 'Research'],
    description: 'President\'s PhD Scholarships at one of the world\'s top STEM universities.',
    fields: ['Engineering', 'Science', 'Medicine', 'Business'],
  },
  {
    id: '73',
    name: 'UCL Global Excellence Scholarship',
    provider: 'University College London',
    country: 'United Kingdom',
    amount: '£15,000',
    levels: ['master'],
    deadline: 'May 1',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['UCL', 'Excellence', 'London'],
    description: 'UCL\'s competitive scholarships recognising global excellence.',
    fields: ['All fields'],
  },
  {
    id: '74',
    name: 'King\'s College London Scholarship',
    provider: 'King\'s College London',
    country: 'United Kingdom',
    amount: '£5,000–£10,000',
    levels: ['master'],
    deadline: 'Apr 1',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['King\'s College', 'London', 'Merit'],
    description: 'Merit scholarships for international students at King\'s College London.',
    fields: ['All fields'],
  },
  {
    id: '75',
    name: 'Leeds International Scholarship',
    provider: 'University of Leeds',
    country: 'United Kingdom',
    amount: '£2,000–£10,000',
    levels: ['master'],
    deadline: 'Jun 30',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Leeds', 'UK', 'Merit'],
    description: 'Multiple scholarships for international students at the University of Leeds.',
    fields: ['All fields'],
  },

  // ── SCANDINAVIA & NORTHERN EUROPE ────────────────────────────────────────────
  {
    id: '76',
    name: 'Lund University Global Scholarship',
    provider: 'Lund University',
    country: 'Sweden',
    amount: 'Full tuition waiver',
    levels: ['master'],
    deadline: 'Feb 1',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Sweden', 'University', 'Merit'],
    description: 'Scholarships for non-EU/EEA students at Lund University.',
    fields: ['All fields'],
  },
  {
    id: '77',
    name: 'University of Oslo Merit Scholarship',
    provider: 'University of Oslo',
    country: 'Norway',
    amount: 'Full tuition',
    levels: ['master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Norway', 'Nordic', 'Merit'],
    description: 'Merit-based scholarships for international students in Norway.',
    fields: ['All fields'],
  },
  {
    id: '78',
    name: 'Copenhagen University Scholarship',
    provider: 'University of Copenhagen',
    country: 'Denmark',
    amount: 'Full tuition waiver',
    levels: ['master'],
    deadline: 'Feb 1',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Denmark', 'Nordic', 'Research'],
    description: 'Scholarships for outstanding non-EU master\'s students at Copenhagen.',
    fields: ['All fields'],
  },
  {
    id: '79',
    name: 'University of Helsinki Scholarship',
    provider: 'University of Helsinki',
    country: 'Finland',
    amount: 'Full tuition waiver',
    levels: ['master'],
    deadline: 'Jan 16',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Finland', 'Nordic', 'University'],
    description: 'Scholarships for international students in English-taught master\'s programmes.',
    fields: ['All fields'],
  },

  // ── REST OF EUROPE ───────────────────────────────────────────────────────────
  {
    id: '80',
    name: 'TU Delft Excellence Scholarship',
    provider: 'Delft University of Technology',
    country: 'Netherlands',
    amount: '€25,000/year',
    levels: ['master'],
    deadline: 'Jan 15',
    minCGPA: 3.5,
    minIELTS: 6.5,
    tags: ['Engineering', 'Technology', 'Netherlands'],
    description: 'Highly competitive scholarships for the best students worldwide at TU Delft.',
    fields: ['Engineering', 'Technology', 'Architecture', 'Science'],
  },
  {
    id: '81',
    name: 'Wageningen University Fellowship',
    provider: 'Wageningen University & Research',
    country: 'Netherlands',
    amount: 'Full tuition + €700/month',
    levels: ['master'],
    deadline: 'Feb 1',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Agriculture', 'Netherlands', 'Environment'],
    description: 'Fellowships for students from developing countries in food and environment.',
    fields: ['Agriculture', 'Environmental Sciences', 'Food Technology', 'Life Sciences'],
  },
  {
    id: '82',
    name: 'Sciences Po Excellence Scholarship',
    provider: 'Sciences Po Paris',
    country: 'France',
    amount: 'Full tuition + €750/month',
    levels: ['master'],
    deadline: 'Jan 10',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['France', 'Social Sciences', 'Elite'],
    description: 'Elite scholarships at Sciences Po for global social science leaders.',
    fields: ['Political Science', 'Economics', 'Law', 'Social Sciences'],
  },
  {
    id: '83',
    name: 'HEC Paris MBA Scholarship',
    provider: 'HEC Paris',
    country: 'France',
    amount: 'Up to €30,000',
    levels: ['master'],
    deadline: 'Mar 1',
    minCGPA: 3.3,
    minIELTS: 7.0,
    tags: ['Business', 'France', 'MBA'],
    description: 'Merit scholarships for exceptional MBA students at HEC Paris.',
    fields: ['Business', 'Management', 'Finance'],
  },
  {
    id: '84',
    name: 'Technical University of Munich Scholarship',
    provider: 'Technical University of Munich',
    country: 'Germany',
    amount: '€12,300/year',
    levels: ['master'],
    deadline: 'May 1',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Germany', 'Engineering', 'STEM'],
    description: 'Max Weber Program scholarships for elite international students at TUM.',
    fields: ['Engineering', 'Science', 'Technology', 'Business'],
  },
  {
    id: '85',
    name: 'University of Vienna Scholarship',
    provider: 'University of Vienna',
    country: 'Austria',
    amount: '€900/month',
    levels: ['master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Austria', 'Europe', 'Research'],
    description: 'University of Vienna\'s scholarship for outstanding international students.',
    fields: ['Humanities', 'Sciences', 'Law', 'All fields'],
  },
  {
    id: '86',
    name: 'Maastricht University High Potential Scholarship',
    provider: 'Maastricht University',
    country: 'Netherlands',
    amount: '€11,000',
    levels: ['master'],
    deadline: 'Feb 1',
    minCGPA: 3.5,
    minIELTS: 6.5,
    tags: ['Netherlands', 'High Potential', 'Merit'],
    description: 'For the brightest non-EU/EEA students applying to UM master\'s programmes.',
    fields: ['All fields'],
  },
  {
    id: '87',
    name: 'University of Amsterdam Excellence Scholarship',
    provider: 'University of Amsterdam',
    country: 'Netherlands',
    amount: '€25,000',
    levels: ['master'],
    deadline: 'Jan 15',
    minCGPA: 3.5,
    minIELTS: 6.5,
    tags: ['Netherlands', 'Amsterdam', 'Excellence'],
    description: 'Highly selective scholarship for top international master\'s students at UvA.',
    fields: ['All fields'],
  },
  {
    id: '88',
    name: 'Radboud Scholarship Program',
    provider: 'Radboud University',
    country: 'Netherlands',
    amount: '€22,500/year',
    levels: ['master'],
    deadline: 'Feb 1',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Netherlands', 'Research', 'Merit'],
    description: 'Scholarships for talented non-EEA students at Radboud University.',
    fields: ['All fields'],
  },

  // ── REST OF WORLD ────────────────────────────────────────────────────────────
  {
    id: '89',
    name: 'ANU Chancellor\'s International Scholarship',
    provider: 'Australian National University',
    country: 'Australia',
    amount: 'Up to 100% tuition',
    levels: ['bachelor', 'master'],
    deadline: 'Oct 31',
    minCGPA: 3.5,
    minIELTS: 7.0,
    tags: ['Australia', 'Merit', 'Elite'],
    description: 'ANU\'s most prestigious scholarship rewarding academic excellence.',
    fields: ['All fields'],
  },
  {
    id: '90',
    name: 'University of Sydney International Scholarship',
    provider: 'University of Sydney',
    country: 'Australia',
    amount: 'AUD $10,000–$40,000',
    levels: ['master', 'phd'],
    deadline: 'Jul 31',
    minCGPA: 3.3,
    minIELTS: 6.5,
    tags: ['Australia', 'Sydney', 'University'],
    description: 'Range of scholarships for international students at the University of Sydney.',
    fields: ['All fields'],
  },
  {
    id: '91',
    name: 'Russia Government Scholarship',
    provider: 'Russian Federal Agency for Education',
    country: 'Russia',
    amount: 'Full tuition + RUB 1,500/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Mar 10',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Russia', 'Government', 'STEM'],
    description: 'Russian federal scholarships for international students at leading Russian universities.',
    fields: ['Engineering', 'Sciences', 'Medicine', 'All fields'],
  },
  {
    id: '92',
    name: 'Brazilian Government Science Without Borders',
    provider: 'Brazilian Government (CNPq/CAPES)',
    country: 'Brazil',
    amount: 'Full funding + BRL 870/month',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Ongoing',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Brazil', 'STEM', 'Latin America'],
    description: 'Brazil\'s flagship international mobility scholarship for STEM students.',
    fields: ['Engineering', 'Sciences', 'Technology', 'Mathematics'],
  },
  {
    id: '93',
    name: 'Israel Government Scholarship (MFAS)',
    provider: 'Israeli Ministry of Foreign Affairs',
    country: 'Israel',
    amount: 'Full tuition + ILS 2,600/month',
    levels: ['master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Israel', 'Government', 'Innovation'],
    description: 'Israeli government scholarships for students at leading Israeli universities.',
    fields: ['All fields'],
  },
  {
    id: '94',
    name: 'México AMEXCID Scholarship',
    provider: 'Mexican Agency for International Development',
    country: 'Mexico',
    amount: 'Full tuition + MXN 8,000/month',
    levels: ['master', 'phd'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Mexico', 'Latin America', 'Government'],
    description: 'Mexican government scholarship for international students at top Mexican universities.',
    fields: ['All fields'],
  },
  {
    id: '95',
    name: 'Argentina Government Scholarship (MINCYT)',
    provider: 'Argentine Ministry of Science',
    country: 'Argentina',
    amount: 'Full tuition + ARS stipend',
    levels: ['master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Argentina', 'Latin America', 'Research'],
    description: 'Scholarships for research-based graduate studies in Argentina.',
    fields: ['Sciences', 'Engineering', 'Medicine', 'All fields'],
  },
  {
    id: '96',
    name: 'Chile ANID Scholarship',
    provider: 'Chilean National Research Agency',
    country: 'Chile',
    amount: 'Full tuition + USD 1,400/month',
    levels: ['master', 'phd'],
    deadline: 'Jun 30',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Chile', 'Research', 'Latin America'],
    description: 'Fully-funded scholarships for graduate research studies in Chile.',
    fields: ['Sciences', 'Engineering', 'Humanities', 'Social Sciences'],
  },
  {
    id: '97',
    name: 'Ethiopian Government Scholarship',
    provider: 'Ethiopian Ministry of Education',
    country: 'Ethiopia',
    amount: 'Full tuition + ETB stipend',
    levels: ['master', 'phd'],
    deadline: 'May 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Africa', 'Ethiopia', 'Development'],
    description: 'Ethiopian government scholarships for African students at Ethiopian universities.',
    fields: ['Agriculture', 'Engineering', 'Public Health', 'All fields'],
  },
  {
    id: '98',
    name: 'South Africa NRF Scholarship',
    provider: 'National Research Foundation South Africa',
    country: 'South Africa',
    amount: 'ZAR 30,000–ZAR 100,000/year',
    levels: ['master', 'phd'],
    deadline: 'Aug 31',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['South Africa', 'Research', 'Africa'],
    description: 'South African government research scholarships for graduate students.',
    fields: ['Sciences', 'Engineering', 'Social Sciences', 'All fields'],
  },
  {
    id: '99',
    name: 'Ghana Government Scholarship',
    provider: 'Ghana Scholarship Secretariat',
    country: 'Ghana',
    amount: 'Full tuition + allowances',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Jul 31',
    minCGPA: 2.8,
    minIELTS: 6.0,
    tags: ['Ghana', 'West Africa', 'Government'],
    description: 'Ghana government scholarships for Ghanaian students to study abroad.',
    fields: ['All fields'],
  },
  {
    id: '100',
    name: 'Nigerian Government Scholarship (BEA)',
    provider: 'Federal Government of Nigeria',
    country: 'Nigeria',
    amount: 'Full funding',
    levels: ['master', 'phd'],
    deadline: 'Aug 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Nigeria', 'West Africa', 'Government'],
    description: 'Nigeria\'s Bilateral Education Agreement scholarships for study abroad.',
    fields: ['All fields'],
  },
  {
    id: '101',
    name: 'Kenya Government Scholarship',
    provider: 'Kenya Higher Education Loans Board',
    country: 'Kenya',
    amount: 'Full tuition + stipend',
    levels: ['master', 'phd'],
    deadline: 'Sep 30',
    minCGPA: 2.8,
    minIELTS: 6.0,
    tags: ['Kenya', 'East Africa', 'Government'],
    description: 'Kenyan government scholarships for outstanding Kenyan and African students.',
    fields: ['All fields'],
  },
  {
    id: '102',
    name: 'Bangladesh Government Scholarship',
    provider: 'Bangladesh Ministry of Education',
    country: 'Bangladesh',
    amount: 'Full tuition + BDT stipend',
    levels: ['master', 'phd'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Bangladesh', 'South Asia', 'Government'],
    description: 'Bangladesh government scholarships under bilateral agreements for study abroad.',
    fields: ['STEM', 'Agriculture', 'Public Health', 'All fields'],
  },
  {
    id: '103',
    name: 'Pakistan HEC Overseas Scholarship',
    provider: 'Higher Education Commission Pakistan',
    country: 'Pakistan',
    amount: 'Full funding',
    levels: ['master', 'phd'],
    deadline: 'Mar 1',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Pakistan', 'South Asia', 'Research'],
    description: 'HEC\'s flagship overseas scholarship for Pakistani students pursuing PhDs abroad.',
    fields: ['STEM', 'Social Sciences', 'Business', 'All fields'],
  },
  {
    id: '104',
    name: 'Sri Lanka Government Scholarship',
    provider: 'University Grants Commission Sri Lanka',
    country: 'Sri Lanka',
    amount: 'Full funding',
    levels: ['master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Sri Lanka', 'South Asia', 'Government'],
    description: 'Sri Lanka government scholarships for academic excellence and development.',
    fields: ['All fields'],
  },
  {
    id: '105',
    name: 'Vietnam Government Scholarship',
    provider: 'Vietnamese Ministry of Education',
    country: 'Vietnam',
    amount: 'Full funding + stipend',
    levels: ['master', 'phd'],
    deadline: 'Apr 15',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Vietnam', 'Southeast Asia', 'Government'],
    description: 'Vietnamese government scholarships for outstanding students to study abroad.',
    fields: ['STEM', 'Agriculture', 'Public Health', 'Economics', 'All fields'],
  },
  {
    id: '106',
    name: 'Philippines DOST Scholarship',
    provider: 'Department of Science and Technology Philippines',
    country: 'Philippines',
    amount: 'Full tuition + PHP 18,000/month',
    levels: ['master', 'phd'],
    deadline: 'Feb 28',
    minCGPA: 3.0,
    minIELTS: 6.0,
    tags: ['Philippines', 'STEM', 'Southeast Asia'],
    description: 'DOST scholarships for Filipino students to pursue STEM graduate degrees.',
    fields: ['Science', 'Technology', 'Engineering', 'Mathematics'],
  },
  {
    id: '107',
    name: 'Colombia Colfuturo Scholarship',
    provider: 'Colfuturo Colombia',
    country: 'Colombia',
    amount: 'Up to USD $40,000/year',
    levels: ['master', 'phd'],
    deadline: 'Apr 30',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Colombia', 'Latin America', 'Education'],
    description: 'Colombian grant-loans for studying master\'s and doctoral programmes abroad.',
    fields: ['All fields'],
  },
  {
    id: '108',
    name: 'Peru Beca 18',
    provider: 'PRONABEC Peru',
    country: 'Peru',
    amount: 'Full funding',
    levels: ['bachelor', 'master'],
    deadline: 'Aug 31',
    minCGPA: 2.5,
    minIELTS: 6.0,
    tags: ['Peru', 'Latin America', 'Opportunity'],
    description: 'Peruvian scholarship for talented students from vulnerable situations.',
    fields: ['Engineering', 'Sciences', 'Technology', 'All fields'],
  },
  {
    id: '109',
    name: 'Uzbekistan Government Scholarship',
    provider: 'Uzbekistan Ministry of Higher Education',
    country: 'Uzbekistan',
    amount: 'Full tuition + stipend',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Jun 15',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Uzbekistan', 'Central Asia', 'Government'],
    description: 'Uzbekistan government scholarships for international students.',
    fields: ['All fields'],
  },
  {
    id: '110',
    name: 'Kazakhstan Bolashak Scholarship',
    provider: 'Kazakhstan Government',
    country: 'Kazakhstan',
    amount: 'Full funding + living allowance',
    levels: ['master', 'phd'],
    deadline: 'Mar 31',
    minCGPA: 3.0,
    minIELTS: 6.5,
    tags: ['Kazakhstan', 'Central Asia', 'Government'],
    description: 'Kazakhstan\'s prestigious international scholarship for Kazakh citizens.',
    fields: ['All fields'],
  },
  {
    id: '111',
    name: 'Ukraine Government Scholarship',
    provider: 'Ukrainian Ministry of Education',
    country: 'Ukraine',
    amount: 'Full tuition + UAH stipend',
    levels: ['bachelor', 'master', 'phd'],
    deadline: 'Apr 15',
    minCGPA: 2.8,
    minIELTS: 5.5,
    tags: ['Ukraine', 'Eastern Europe', 'Government'],
    description: 'Ukrainian government scholarships for international students at Ukrainian universities.',
    fields: ['Medicine', 'Engineering', 'Sciences', 'All fields'],
  },
  {
    id: '112',
    name: 'ANU Futures Scholarship',
    provider: 'Australian National University',
    country: 'Australia',
    amount: 'AUD $10,000/year',
    levels: ['bachelor', 'master'],
    deadline: 'Sep 30',
    minCGPA: 3.2,
    minIELTS: 6.5,
    tags: ['Australia', 'ANU', 'Merit'],
    description: 'ANU Futures Scholarship for academically excellent international students.',
    fields: ['All fields'],
  },
];

/** Match score 0–100 based on profile vs scholarship requirements. */
export function computeMatchScore(
  s: Scholarship,
  profile: { cgpa4: number; ielts: number; level: string },
): number {
  let score = 100;

  // CGPA gap penalty
  if (profile.cgpa4 > 0) {
    const gap = s.minCGPA - profile.cgpa4;
    if (gap > 0) score -= Math.min(50, gap * 20);
  } else {
    score -= 30;
  }

  // IELTS gap penalty
  if (profile.ielts > 0) {
    const gap = s.minIELTS - profile.ielts;
    if (gap > 0) score -= Math.min(30, gap * 10);
  } else {
    score -= 20;
  }

  // Degree level mismatch
  if (profile.level && !s.levels.includes(profile.level as never)) {
    score -= 40;
  }

  return Math.max(1, Math.round(score));
}

export function getMatchLabel(score: number): string {
  if (score >= 75) return 'Excellent';
  if (score >= 50) return 'Competitive';
  return 'Long Shot';
}
